### ISSUE TITLE
listing1.01.jl  @quickactivate "StatisticsWithJulisPlutoNotebooks"  spelling error

### ISSUE THREAD

**Issue by rleyvasal** [StatisticalRethinkingJulia/StatisticsWithJuliaPlutoNotebooks.jl#1]
Notebooks in folder 01 have to wrong spelling on @quickactivate 

should read: 

"StatisticsWithJuliaPlutoNotebooks"

but is spelled:

"StatisticsWithJulisPlutoNotebooks"

**Comment by goedman** [comment]
Oops, thank you very much! Should be fixed in the repository now.
