### ISSUE TITLE
listing5.04.jl  and  beyond  don't the code

### ISSUE THREAD

**Issue by rleyvasal** [StatisticalRethinkingJulia/StatisticsWithJuliaPlutoNotebooks.jl#2]
listing5.04.jl   and all the files after(listing5.05.jl,  etc)  don't have the code for the excercise

They all show the same code below:

using Pkg, DrWatsonusing Pkg, DrWatson
begin
	@quickactivate "StatisticsWithJuliaPlutoNotebooks"
	using Random, Distributions, Plots
	Random.seed!(0)
end
md"## End of listing5.02"

**Comment by goedman** [comment]
Yes, that's correct.  I need to convert and add those.

**Comment by goedman** [comment]
Hi @rleyvasal  Just added these (I got stuck a few weeks ago on digamma() in listing 5.10).
